- name: Install dependency packages
  yum: name="{{ item }}" state=present
  with_items:
    - "httpd"
    - "java-1.8.0-openjdk.x86_64"
    - "unzip"
    - "subversion"

- name: Add tomcat group
  group: name=tomcat state=present

- name: Add tomcat user
  user:
    name: tomcat
    group: tomcat
    shell: /bin/nologin

- name: Check if tomcat has been installed already.
  stat:
    path: "{{ tomcat['home'] }}/conf"
  register: tomcat_install_path_status

- name: Obtain and decompress tomcat
  unarchive:
    src: "{{ tomcat['package_location'] }}"
    dest: /tmp
    remote_src: "{{ tomcat['remote'] }}"
  when: tomcat_install_path_status.stat.isdir is not defined

- name: Create tomcat home folder
  file:
    path: "{{ tomcat['home'] }}"
    state: directory
    owner: tomcat
    group: tomcat

- name: Copy tomcat to its home
  shell: "cp -R /tmp/{{ tomcat['version'] }}/* {{ tomcat['home'] }}"
  when: tomcat_install_path_status.stat.isdir is not defined
  notify:
    - restart tomcat

- name: Copy tomcat admin user configuration
  template:
    src: tomcat-users.xml.j2
    dest: "{{ tomcat['home']}}/conf/tomcat-users.xml"
  notify:
    - restart tomcat

- name: Set tomcat user as owner of tomcat related files
  file:
    path: "{{ tomcat['home'] }}"
    owner: tomcat
    group: tomcat
    recurse: yes
    mode: 'g+rw'

- name: Permissions tomcat conf and bin content
  file:
    path: "{{ tomcat['home'] }}/{{ item }}"
    mode: 'g+r'
    recurse: yes
  with_items:
    - conf
    - bin

- name: Permissions tomcat conf and bin folder
  file:
    path: "{{ tomcat['home'] }}/{{ item }}"
    mode: 'g+rwx'
  with_items:
    - conf
    - bin

- name: Create tomcat systemd unit
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify:
    - reload systemd daemon
    - restart tomcat

- name: Start tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: yes
