---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Creación del grupo de parametros para MySQL"
      rds_param_group:
        aws_access_key: "{{ m_access_key }}"
        aws_secret_key: "{{ m_secret_key }}"
        region: "{{ m_region }}"
        state: present
        name: geonetwork-custom
        description: "Parametros para el funcionamiento de geonetwork"
        engine: 'mysql5.6'
        params:
          lower_case_table_names: "1"

    - name: Aprovisionamiento de la base de datos
      rds:
        #wait: true
        aws_access_key: "{{ m_access_key }}"
        aws_secret_key: "{{ m_secret_key }}"
        command: create
        instance_name: "{{ db_instance_name }}"
        region: "{{ m_region }}"
        db_name: "{{ db_db_name }}"
        db_engine: MySQL
        instance_type: "{{ db_instance_type }}"
        size: "{{ db_size }}"
        parameter_group: geonetwork-custom
        username: "{{ db_username }}"
        password: "{{ db_password }}"
        tags:
          Environment: testing
          Application: geonetwork
